### PR TITLE
Gradle 2.x compatibility

### PR DESCRIPTION
**Pull request by macedigital**
* fix classpath issue in `runMod` task
* update gradle to version 2.2
* make `vertx.gradle` compatible with recent changes in groovy
* use https when connecting with sonatype
* add explicit dependencies and pin versions

PR is inspired by https://github.com/vert-x/vertx-gradle-template/issues/32, https://github.com/vert-x/vertx-gradle-template/pull/37, https://github.com/vert-x/vertx-gradle-template/pull/36, https://github.com/vert-x/vertx-gradle-template/pull/29 and most importantly https://github.com/vert-x/vertx-gradle-template/pull/31.

If this PR gets accepted, `runMod` task should run way more smoothly and be more resilient to custom environment settings than before. JRuby still remains very fickle even compared to minor differences in build environments, but that is definitely outside the scope of this PR.

Anyway, I am open for ideas or suggestions.

Btw: I signed the Eclipse CLA (User: madler6j2).

### CODE REVIEW

**Comment by RowanKaag** [comment]
merge this please

**Comment by mohamnag** [comment]
is this repo dead or is there an specific reason that you dont update the gradle version?

**Comment by purplefox** [comment]
I didn't know about this because my GitHub notifications were until recently getting swallowed by my spam filter :(

**Comment by mohamnag** [comment]
thanks ;)

**Pull request merged**
